apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-config
  labels:
    app: edge-service
data:
  application.yml: |
    spring:
      data:
        redis:
          host: polar-redis
      security:
        oauth2:
          client:
            provider:
              keycloak:
                issuer-uri: http://polar-keycloak/realms/PolarBookshop